config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', LoginView.as_view(), name='login'),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('library/', include('core.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import *

urlpatterns = [
    path('' , FolderListView.as_view(), name='folder_list'),
    path('search/', FileSearchView.as_view(), name='file_search'),
    path('folder_create/' , FolderCreateView.as_view(), name='folder_create'),
    path('upload_file/', FileUploadView.as_view(), name='upload_file'),
    path('delete-folder/<int:pk>/', FolderDeleteView.as_view(), name='delete_folder'),
    path('delete-file/<int:pk>/', FileDeleteView.as_view(), name='delete_file'),
    path('folder/update_name/', FolderUpdateView.as_view(), name='folder_update_name'),
    path('file/update/', FileUpdateView.as_view(), name='file_update'),

]

core/models.py
import mimetypes
from django.db import models

from core.validators import validate_file


# Create your models here.
class Folder(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'folder'
        verbose_name_plural = 'folders'

    def get_path(self):
        path = [self]
        parent = self.parent
        while parent:
            path.append(parent)
            parent = parent.parent
        return list(reversed(path))


class File(models.Model):
    TYPE_CHOICES = (
        ('image', 'image'),
        ('video', 'video'),
    )
    name = models.CharField(max_length=100, db_index=True)
    file = models.FileField(upload_to='files', validators=[validate_file])
    file_type = models.CharField(max_length=100, choices=TYPE_CHOICES, db_index=True)
    size = models.PositiveBigIntegerField(editable=False)
    folder = models.ForeignKey(Folder , on_delete=models.CASCADE, null=True, blank=True, related_name='files')

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.size = self.file.size
            mime_type, _ = mimetypes.guess_type(self.file.name)
            if mime_type and mime_type.startswith('image'):
                self.file_type = 'image'
            elif mime_type and mime_type.startswith('video'):
                self.file_type = 'video'
            else:
                self.file_type = 'unknown'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'file'
        verbose_name_plural = 'files'
        unique_together = (('name', 'file_type'),)

core/forms.py
from django import forms

from core.models import File , Folder
from core.validators import validate_file


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['name' , 'file' , 'file_type']
        file = forms.FileField(validators=[validate_file])

core/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView
from django.views.generic import View

from .forms import FileUploadForm
from .models import File, Folder


class FolderListView(LoginRequiredMixin, ListView):
    model = Folder
    template_name = 'core/folder_list.html'
    context_object_name = 'folders'

    def get_queryset(self):
        parent_id = self.request.GET.get('folder')
        return Folder.objects.filter(

            parent_id=parent_id
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        parent_id = self.request.GET.get('folder')
        context['files'] = File.objects.filter(
            folder_id=parent_id
        )
        if parent_id:
            folder = get_object_or_404(Folder, id=parent_id)
            context['breadcrumbs'] = folder.get_path()
        return context


class FileUploadView(LoginRequiredMixin, CreateView):
    model = File
    form_class = FileUploadForm
    template_name = 'core/partial/file_upload.html'
    success_url = reverse_lazy('folder_list')

    def form_valid(self, form):
        folder_id = self.request.POST.get('folder')
        if folder_id:
            folder = get_object_or_404(Folder, id=folder_id)
            form.instance.folder = folder
        return super().form_valid(form)


class FolderCreateView(LoginRequiredMixin, CreateView):
    model = Folder
    fields = ['name']
    template_name = 'core/partial/folder_create.html'
    success_url = reverse_lazy('folder_list')


class FolderDeleteView(LoginRequiredMixin, DeleteView):
    model = Folder
    success_url = reverse_lazy('folder_list')

    def delete(self, request, *args, **kwargs):
        folder = self.get_object()
        folder.delete()
        return JsonResponse({'success': True})


class FileDeleteView(LoginRequiredMixin, DeleteView):
    model = File
    success_url = reverse_lazy('folder_list')

    def delete(self, request, *args, **kwargs):
        file = self.get_object()
        file.delete()
        return JsonResponse({'success': True})


class FolderUpdateView(View):
    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)
            folder_id = data.get('folder_id')
            new_name = data.get('name')

            folder = Folder.objects.get(id=folder_id)
            folder.name = new_name
            folder.save()

            return JsonResponse({'success': True, 'new_name': folder.name})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)}, status=400)


class FileUpdateView(View):
    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)
            file_id = data.get('file_id')
            new_name = data.get('name')
            print(file_id, new_name)

            file = File.objects.get(id=file_id)
            file.name = new_name
            print(file.name)
            file.save()
            return JsonResponse({'success': True, 'new_name': file.name})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)}, status=400)


class FileSearchView(LoginRequiredMixin, ListView):
    model = File
    template_name = 'core/partial/search_results.html'
    context_object_name = 'files'
    paginate_by = 20

    def get_queryset(self):
        query = self.request.GET.get('search', '').strip()
        folder_id = self.request.GET.get('folder')

        if not query:
            return File.objects.none()
        lookups = Q(name__icontains=query)
        if folder_id:
            lookups &= Q(folder_id=folder_id)
        return File.objects.filter(lookups).order_by('-datetime_created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_term'] = self.request.GET.get('search', '')
        context['current_folder'] = self.request.GET.get('folder')
        return context

        results = []
        for file in files:
            results.append({
                'id': file.id,
                'name': file.name,
                'type': file.file_type,
                'size': file.size,
                'created': file.datetime_created.strftime('%Y/%m/%d')
            })

        return JsonResponse({'files': results})

core/templates/core/partial/file_update_name.html
<div class="modal fade" id="renameFileModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Chane Name</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="renameFileForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="hidden" name="file_id" id="file_id" value="{{ file.id }}">
                        <label for="file_name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="file_name" name="name" value="{{ file.name }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

core/templates/core/partial/file_upload.html
<div class="modal fade" id="uploadModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Upload File</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'upload_file' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="folder" value="{{ request.GET.folder }}">
                    <div class="mb-3">
                        <label for="id_name">Name:</label>
                        <input type="text" name="name" maxlength="100" required="" id="id_name">
                    </div>

                    <div class="mb-3">
                        <label for="id_file">File:</label>
                        <input type="file" class="form-control" name="file" accept="image/*,video/*" required>
                        <div class="form-text">
                            Maximum size allowed: images 10 MB, videos 50 MB
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="id_file_type">File type:</label>
                        <select name="file_type" required="" id="id_file_type">
                            <option value="" selected="">---------</option>
                            <option value="image">Image</option>
                            <option value="video">Video</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
    </div>
</div>

core/templates/core/partial/folder_create.html
<div class="modal fade" id="newFolderModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Folder</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'folder_create' %}">
                    {% csrf_token %}
                    <input type="hidden" name="parent" value="{{ request.GET.folder }}">
                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" required>
                    </div>
                    <button type="submit" class="btn btn-success">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

core/templates/core/partial/folder_update_name.html
<div class="modal fade" id="renamefModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Change name Folder</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="renameFolderForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="hidden" name="folder_id" value="{{ folder.id }}">
                        <label for="folder_name" class="form-label">Name </label>
                        <input type="text" class="form-control" id="folder_name" name="name" value="{{ folder.name }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

core/templates/core/partial/search_results.html
{% extends '_base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row mb-4">
            <div class="col">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active">Resualt search of "{{ search_term }}"</li>
                    </ol>
                </nav>
            </div>
        </div>

        {% if files %}
            <div class="row">
                <div class="col">
                    <h5>{{ files|length }} Find file</h5>
                </div>
            </div>

            <div class="row g-4">
                {% for file in files %}
                    <div class="col-md-12">
                        <div class="file-card h-100">
                            <div class="card-body row">
                                <div class="col-lg-3 col-sm-12">
                                    {% if file.file_type == 'image' %}
                                        <img src="{{ file.file.url }}" alt="{{ file.name }}" class="thumbnail">
                                    {% endif %}
                                    <h5 class="card-title mt-2">{{ file.name }}</h5>
                                </div>

                                <div class="col-lg-2">
                                    {{ file.datetime_created|date:"Y/m/d" }}
                                </div>

                                <div class="col-lg-1">
                                    {{ file.size|filesizeformat }}
                                </div>

                                <div class="col-lg-1">
                                    {{ file.get_file_type_display }}
                                </div>

                                <div class="col-lg-2">
                                    <div class="btn-group">
                                        <a href="{{ file.file.url }}" class="btn btn-sm btn-primary" target="_blank">
                                            View
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {% if is_paginated %}
                <div class="row mt-4">
                    <div class="col">
                        <nav aria-label="Page navigation">
                            <ul class="pagination justify-content-center">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?search={{ search_term }}&page={{ page_obj.previous_page_number }}{% if current_folder %}&folder={{ current_folder }}{% endif %}">
                                            Back
                                        </a>
                                    </li>
                                {% endif %}

                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <li class="page-item active">
                                            <span class="page-link">{{ num }}</span>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a class="page-link" href="?search={{ search_term }}&page={{ num }}{% if current_folder %}&folder={{ current_folder }}{% endif %}">
                                                {{ num }}
                                            </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?search={{ search_term }}&page={{ page_obj.next_page_number }}{% if current_folder %}&folder={{ current_folder }}{% endif %}">
                                            Forward
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}

        {% else %}
            <div class="row">
                <div class="col text-center">
                    <h5>Nothing find</h5>
                    <p class="text-muted">Please search with other keywords</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}